# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
- name: Deploy Gaudi Firmware Driver
  hosts: kube_control_plane
  vars:
    ansible_python_interpreter: /usr/bin/python3
    remote_home_dir: "{{ lookup('env', 'PWD') }}/scripts"
  gather_facts: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  environment: "{{ proxy_disable_env | default({}) }}"
  tasks:
    - name: Ensure pip is installed
      ansible.builtin.package:
        name: python3-pip
        state: present
      become: true
    - name: Install kubernetes library using pip
      ansible.builtin.pip:
        name: kubernetes
        state: present
        executable: /usr/bin/pip3
      become: true
    - name: Update Drivers
      become: yes
      script: "{{ remote_home_dir }}/gaudi-firmware-driver-updater.sh --drivers"
      when: update_type == "drivers"
    - name: Update Firmware
      become: yes
      script: "{{ remote_home_dir }}/gaudi-firmware-driver-updater.sh --firmware"
      when: update_type == "firmware"
    - name: Update Drivers and Firmware
      become: yes
      script: "{{ remote_home_dir }}/gaudi-firmware-driver-updater.sh --both"
      when: update_type == "both"
