# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.global.monitoring }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "teirerank.fullname" . }}-service
  labels:
    release: {{ .Values.global.prometheusRelease }}
spec:
  selector:
    matchLabels:
      {{- include "teirerank.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: teirerank
    interval: 5s
{{- end }}
