# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Config_Watch On
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
        Parsers_File /opt/bitnami/fluent-bit/conf/parsers.conf
        Parsers_File /opt/bitnami/fluent-bit/conf/custom_parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On

    [OUTPUT]
        Name              es
        Match             *
        Host              logging-elasticsearch.observability.svc.cluster.local
        Port              9200
        Logstash_Format   On
        Logstash_Prefix   fluent-bit
        Replace_Dots      On
        Retry_Limit       False
        Suppress_Type_Name On
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: logging-fluentbit
    meta.helm.sh/release-namespace: observability  
  labels:
    app.kubernetes.io/instance: logging-fluentbit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: logging-fluentbit
    app.kubernetes.io/part-of: logging-fluentbit   
    helm.sh/chart: fluent-bit-2.5.5
  name: logging-fluentbit-fluent-bit-config
  namespace: observability  

