# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

fluent-bit:
  securityContext:
    fsGroup: 2000
    fsGroupChangePolicy: "Always" 

service:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2020"

extraVolumes:
  - name: varlog
    hostPath:
      path: /var/log
      type: Directory

extraVolumeMounts:
  - name: varlog
    mountPath: /var/log
    readOnly: false

containerSecurityContext:
  runAsUser: 2000
  runAsGroup: 2000
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

parsers:
  customParsers: |
    # CRI-O Parser
    [PARSER]
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<log>.*)$
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
