      all:
        hosts:
          inference-control-plane-01:
            ansible_host: "{{ private_ip }}"
            ansible_user: "{{ ansible_user }}"
            ansible_ssh_private_key_file: /path/to/your/ssh/key
          inference-control-plane-02:
            ansible_host: "{{ private_ip }}"
            ansible_user: "{{ ansible_user }}"
            ansible_ssh_private_key_file: /path/to/your/ssh/key         
          inference-control-plane-03:
            ansible_host: "{{ private_ip }}"
            ansible_user: "{{ ansible_user }}"
            ansible_ssh_private_key_file: /path/to/your/ssh/key
          inference-workload-node-01:
            ansible_host: "{{ private_ip }}"
            ansible_user: "{{ ansible_user }}"
            ansible_ssh_private_key_file: /path/to/your/ssh/key
          inference-workload-node-02:
            ansible_host: "{{ private_ip }}"
            ansible_user: "{{ ansible_user }}"
            ansible_ssh_private_key_file: /path/to/your/ssh/key
          inference-workload-node-03:
            ansible_host: "{{ private_ip }}"
            ansible_user: "{{ ansible_user }}"
            ansible_ssh_private_key_file: /path/to/your/ssh/key
          inference-workload-node-04:
            ansible_host: "{{ private_ip }}"
            ansible_user: "{{ ansible_user }}"
            ansible_ssh_private_key_file: /path/to/your/ssh/key         
          inference-workload-node-05:
            ansible_host: "{{ private_ip }}"
            ansible_user: "{{ ansible_user }}"
            ansible_ssh_private_key_file: /path/to/your/ssh/key
        children:
          kube_control_plane:
            hosts:
              inference-control-plane-01:
              inference-control-plane-02:
              inference-control-plane-03:
          kube_node:
            hosts:
              inference-workload-node-01:
              inference-workload-node-02:
              inference-workload-node-03:
              inference-workload-node-04:
              inference-workload-node-05:
          etcd:
            hosts:              
              inference-control-plane-01:
              inference-control-plane-02:
              inference-control-plane-03:
          k8s_cluster:
            children:
              kube_control_plane:
              kube_node:
          calico_rr:
            hosts: {}
