# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# APISIX Namespace
namespace: auth-apisix

# APISIX Helm chart configs
apisix:
  version: 2.8.1
  enabled: true
  replicaCount: "" 
  ingress-controller:
    replicaCount: ""
    enabled: true
    config:
      apisix:
        serviceName: auth-apisix-admin
        serviceNamespace: auth-apisix
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: "node-role.kubernetes.io/inference-infra"
                  operator: In
                  values:
                    - "true"
          - weight: 50
            preference:
              matchExpressions:
                - key: "node-role.kubernetes.io/control-plane"
                  operator: Exists
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: auth-apisix
              topologyKey: "kubernetes.io/hostname"
  etcd:
    auth:    
      tls:        
        enabled: false        
    replicaCount: ""
    persistence:
      enabled: true
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: "node-role.kubernetes.io/inference-infra"
                  operator: In
                  values:
                    - "true"
          - weight: 50
            preference:
              matchExpressions:
                - key: "node-role.kubernetes.io/control-plane"
                  operator: Exists
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: auth-apisix
              topologyKey: "kubernetes.io/hostname"    
  dashboard:
    enabled: false

  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: "node-role.kubernetes.io/inference-infra"
                operator: In
                values:
                  - "true"
        - weight: 50
          preference:
            matchExpressions:
              - key: "node-role.kubernetes.io/control-plane"
                operator: Exists
    podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: auth-apisix
              topologyKey: "kubernetes.io/hostname"
    
