apiVersion: v1
kind: Service
metadata:
  name: genai-gateway-service  
  labels:
    app: litellm
spec:
  selector:
    app: litellm
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
