---
# SPDX-FileCopyrightText: (C) 2023 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel

name: Auto Update PR

# On push to the main branch and support branches, update any branches that are out of date
# and have auto-merge enabled. If the branch is currently out of date with the base branch,
# it must be first manually updated and then will be kept up to date on future runs.
on:
  push:
    branches:
      - main
      - release-*

jobs:
  Auto-Update-PR:
    runs-on: generic
    steps:
      - uses: intel-innersource/frameworks.actions.thirdparty.auto-update@v2.2.1